services:
  web:
    image: minha-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8089:10000"
    volumes:
      - sqlite_data:/var/www/html/database
    networks:
      - net_principal
    restart: always

networks:
  net_principal:
    driver: bridge

volumes:
  sqlite_data:
    driver: local
